config/routes.rb
Rails.application.routes.draw do

  root to: "flats#index"
  resources :flats
  resources :flats do
    member do
      patch :move
    end
  end

  delete "flats", to: "flats#destroy_all", as: :destroy_all
  get "flat", to: "flats#seed", as: :seed
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  # before_action :find_flat, only: [:new]

  def index
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name LIKE ?", "%#{params[:query]}%")
    else
      @flats = Flat.all
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new()
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)

  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path(@flat)
  end

  def destroy_all
    @flat = Flat.all
    @flat.destroy_all
    redirect_to flats_path(@flat)
  end

  def seed
    Rails.application.load_seed
    redirect_to flats_path(@flat)
  end

  def move
    @flat = Flat.find(params[:id])
    @flat.insert_at(params[:position].to_i)
    head :ok
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture, :position)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<nav class="navbar sticky-top navbar-light bg-light d-flex justify-content-between">

  <div class="btn navbar-brand  d-inline-block align-top">
    <%= link_to image_tag("airbnb-logo.png", width: "60px"), flats_path %>
  </div>
  <div>
    <%= link_to 'Back to Flats', flats_path, class: "btn btn-outline-success" %>
  </div>

</nav>

<div class="container m-5">
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.input :picture, input_html: { value: 'https://loremflickr.com/250/250/building' } %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/index.html.erb
<nav class="navbar sticky-top navbar-light bg-light d-flex justify-content-between">

  <div class="btn navbar-brand  d-inline-block align-top">
    <%= link_to image_tag("airbnb-logo.png", width: "60px"), flats_path %>
  </div>

  <div class="d-flex ">
    <form class="form-inline mr-4">
      <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="<%= params[:query] %>">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <div>
      <%= link_to 'Delete all Flats', destroy_all_path, method: :delete, data: { confirm: "Are you really sure?" }, class: "btn btn-outline-danger " %>

      <%= link_to 'Seed', seed_path(@flats), class: "btn btn-outline-warning ml-auto" %>

      <%= link_to '+ Add Flat', new_flat_path(@flat), class: "btn btn-primary ml-auto" %>
    </div>
  </div>
</nav>
<div class="container">
  <h1 class="h2 my-3 header">FLATS - <span>[<%= Flat.count %>]</span></h1>
  <% if @query %>
    <p>You searched for <strong><%= @query %></strong>. We found <%= @flats.count %> flats out of
      our <%= Flat.count %> on our website.</p>
  <% else %>
    <p>All <%= Flat.count %> flats.</p>
  <% end %>
</div>


<div class="container">
  <div class="">
    <div class="row col-xs-2 justify-content-between" data-controller="drag" data-drag-url="/flats/:id">
      <% @flats.each do |flat| %>
        <div class="card m-3 w-25" data-id="<%= flat.id %>">
          <img class="card-img-top" src="<%= flat.picture %>" alt="Card image cap">
          <div class="card-body pb-0">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"><%= flat.address %></p>
            <div class="container d-flex p-0">
              <p class="card-text ">
                <i class="fas fa-user-friends p-2"></i><%= flat.number_of_guests %>
              </p>
              <p class="card-text ml-auto"><%= flat.price_per_night %>
                <i class="fas fa-euro-sign"></i>
              </p>
            </div>
          </div>
          <div class="card-footer">
            <small class="text-muted"><%= link_to 'more info', flat_path(flat) %></small>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<nav class="navbar sticky-top navbar-light bg-light d-flex justify-content-between">

  <div class="btn navbar-brand  d-inline-block align-top">
    <%= link_to image_tag("airbnb-logo.png", width: "60px"), flats_path %>
  </div>
  <div>
    <%= link_to 'Back to Flats', flats_path, class: "btn btn-outline-success" %>
  </div>

</nav>


<div class="container m-5">
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.input :picture, input_html: { value: 'https://loremflickr.com/250/250/building' } %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<nav class="navbar sticky-top navbar-light bg-light d-flex justify-content-between">

  <div class="btn navbar-brand  d-inline-block align-top">
    <%= link_to image_tag("airbnb-logo.png", width: "60px"), flats_path %>
  </div>
  <div>
    <%= link_to '+ Add Flat', new_flat_path(@flat), class: "btn btn-primary" %>
  </div>

</nav>


<div class="container">
  <div class="card w-50 mx-auto mt-4">
    <img class="card-img-top" src="<%= @flat.picture %>" alt="Card image cap">
    <div class="card-body pb-0">
      <h5 class="card-title"><%= @flat.name %></h5>
      <p class="card-text"><%= @flat.address %></p>
      <div class="container d-flex p-0">
        <p class="card-text ">
          <i class="fas fa-user-friends p-2"></i><%= @flat.number_of_guests %>
        </p>
        <p class="card-text ml-auto"><%= @flat.price_per_night %>
          <i class="fas fa-euro-sign"></i>
        </p>
      </div>
    </div>
    <div class="card-footer d-flex">
      <div><%= link_to 'Back to Flats', flats_path, class: "btn btn-outline-success" %></div>
      <div class="ml-auto"><%= link_to 'Edit this Flat', edit_flat_path, class: "btn btn-outline-info " %></div>
      <div class="ml-auto"><%= link_to 'Delete this Flat', flat_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger " %></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSimpleAirbnb</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<%= yield %>
</body>
</html>